import { google } from 'googleapis';
import type { Booking } from './supabase';

// Initialize Google Calendar API
const getCalendarClient = () => {
  const credentials = process.env.GOOGLE_SERVICE_ACCOUNT_KEY;

  if (!credentials) {
    console.warn('Google Calendar: GOOGLE_SERVICE_ACCOUNT_KEY not configured');
    return null;
  }

  try {
    const auth = new google.auth.GoogleAuth({
      credentials: JSON.parse(credentials),
      scopes: ['https://www.googleapis.com/auth/calendar'],
    });

    return google.calendar({ version: 'v3', auth });
  } catch (error) {
    console.error('Failed to initialize Google Calendar client:', error);
    return null;
  }
};

// Create a calendar event for a booking
export const createCalendarEvent = async (booking: Booking) => {
  const calendar = getCalendarClient();

  if (!calendar) {
    console.log('Google Calendar not configured, skipping event creation');
    return null;
  }

  try {
    // Parse date and time
    const [year, month, day] = booking.date.split('-');
    const [hours, minutes] = booking.time.split(':');

    // Create datetime strings in ISO format (CET timezone)
    const startDateTime = new Date(
      parseInt(year),
      parseInt(month) - 1,
      parseInt(day),
      parseInt(hours),
      parseInt(minutes)
    );

    // Event duration: 1 hour
    const endDateTime = new Date(startDateTime);
    endDateTime.setHours(endDateTime.getHours() + 1);

    const event = {
      summary: `Consultation: ${booking.topic || 'General Inquiry'}`,
      description: `Consultation with ${booking.name}\n\nEmail: ${booking.email}\nTopic: ${booking.topic || 'General Inquiry'}\n\nGenerated by Sygma Consult booking system.`,
      location: 'Online (Google Meet)',
      start: {
        dateTime: startDateTime.toISOString(),
        timeZone: 'Europe/Paris', // CET
      },
      end: {
        dateTime: endDateTime.toISOString(),
        timeZone: 'Europe/Paris',
      },
      attendees: [
        { email: booking.email, displayName: booking.name },
        { email: process.env.ADMIN_EMAIL || 'contact@sygma-consult.com' },
      ],
      conferenceData: {
        createRequest: {
          requestId: `${booking.id || Date.now()}-${Math.random().toString(36).substring(7)}`,
          conferenceSolutionKey: { type: 'hangoutsMeet' },
        },
      },
      reminders: {
        useDefault: false,
        overrides: [
          { method: 'email', minutes: 24 * 60 }, // 24 hours before
          { method: 'popup', minutes: 60 }, // 1 hour before
        ],
      },
    };

    const response = await calendar.events.insert({
      calendarId: process.env.GOOGLE_CALENDAR_ID || 'primary',
      requestBody: event,
      conferenceDataVersion: 1,
      sendUpdates: 'all', // Send email invitations to all attendees
    });

    console.log('Calendar event created:', response.data.id);

    return {
      eventId: response.data.id,
      htmlLink: response.data.htmlLink,
      meetLink: response.data.conferenceData?.entryPoints?.[0]?.uri || null,
    };
  } catch (error) {
    console.error('Failed to create calendar event:', error);
    return null;
  }
};

// Update a calendar event
export const updateCalendarEvent = async (
  eventId: string,
  updates: Partial<Booking>
) => {
  const calendar = getCalendarClient();

  if (!calendar) {
    console.log('Google Calendar not configured, skipping event update');
    return null;
  }

  try {
    // Get existing event
    const existingEvent = await calendar.events.get({
      calendarId: process.env.GOOGLE_CALENDAR_ID || 'primary',
      eventId,
    });

    if (!existingEvent.data) {
      throw new Error('Event not found');
    }

    // Update fields
    const updatedEvent = { ...existingEvent.data };

    if (updates.date && updates.time) {
      const [year, month, day] = updates.date.split('-');
      const [hours, minutes] = updates.time.split(':');

      const startDateTime = new Date(
        parseInt(year),
        parseInt(month) - 1,
        parseInt(day),
        parseInt(hours),
        parseInt(minutes)
      );

      const endDateTime = new Date(startDateTime);
      endDateTime.setHours(endDateTime.getHours() + 1);

      updatedEvent.start = {
        dateTime: startDateTime.toISOString(),
        timeZone: 'Europe/Paris',
      };
      updatedEvent.end = {
        dateTime: endDateTime.toISOString(),
        timeZone: 'Europe/Paris',
      };
    }

    if (updates.topic) {
      updatedEvent.summary = `Consultation: ${updates.topic}`;
    }

    const response = await calendar.events.update({
      calendarId: process.env.GOOGLE_CALENDAR_ID || 'primary',
      eventId,
      requestBody: updatedEvent,
      sendUpdates: 'all',
    });

    console.log('Calendar event updated:', response.data.id);
    return response.data;
  } catch (error) {
    console.error('Failed to update calendar event:', error);
    return null;
  }
};

// Cancel a calendar event
export const cancelCalendarEvent = async (eventId: string) => {
  const calendar = getCalendarClient();

  if (!calendar) {
    console.log('Google Calendar not configured, skipping event cancellation');
    return null;
  }

  try {
    await calendar.events.delete({
      calendarId: process.env.GOOGLE_CALENDAR_ID || 'primary',
      eventId,
      sendUpdates: 'all', // Notify all attendees
    });

    console.log('Calendar event cancelled:', eventId);
    return true;
  } catch (error) {
    console.error('Failed to cancel calendar event:', error);
    return null;
  }
};
